# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_airtimetopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimetopup',
            name='payment_processor',
            field=models.CharField(blank=True, help_text=b'Payment Processor used', max_length=4, verbose_name=b'Payment Processor', choices=[(b'STRP', b'stripe')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='payment_reference',
            field=models.CharField(help_text=b'Reference generated by payment Processor', max_length=50, verbose_name=b'Payment Reference', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_processor',
            field=models.CharField(blank=True, help_text=b'Payment Processor used', max_length=4, verbose_name=b'Payment Processor', choices=[(b'PAYP', b'paypal'), (b'STRP', b'stripe')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(help_text=b'Reference generated by payment Processor', max_length=50, verbose_name=b'Payment Reference', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='state',
            field=models.CharField(default=b'INIT', help_text=b'State of the transaction.', max_length=4, verbose_name=b'State', choices=[(b'INIT', b'initialized'), (b'PAID', b'paid'), (b'PROC', b'processed'), (b'CANC', b'cancelled'), (b'INVD', b'invalid')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(default=b'INIT', help_text=b'State of the transaction.', max_length=4, verbose_name=b'State', choices=[(b'INIT', b'initialized'), (b'INFO', b'gatering information'), (b'REDY', b'ready for payment'), (b'PAID', b'paid'), (b'PROC', b'processed'), (b'CANC', b'cancelled'), (b'INVD', b'invalid')]),
            preserve_default=True,
        ),
    ]
