# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.utils.timezone import utc
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20150618_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtimetopup',
            options={'ordering': ['-last_changed']},
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='initialized_at',
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='invalidated_at',
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='last_changed',
            field=models.DateTimeField(default=datetime.datetime(2015, 6, 19, 22, 15, 23, 598604, tzinfo=utc), auto_now_add=True, help_text=b'Last changed', verbose_name=b'Last changed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='exchange_rate',
            field=models.ForeignKey(related_name='transaction_airtimetopup', to='pricing.ExchangeRate', help_text=b'Exchange rate applied to this transaction', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='payment_processor',
            field=models.CharField(blank=True, help_text=b'Payment Processor used', max_length=4, verbose_name=b'Payment Processor', choices=[(b'PAYP', b'paypal'), (b'STRP', b'stripe'), (b'WPAY', b'wepay')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='payment_reference',
            field=models.CharField(help_text=b'Reference generated by payment processor', max_length=50, verbose_name=b'Payment Reference', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='recipient',
            field=models.ForeignKey(related_name='transaction_airtimetopup', to='recipient.Recipient', help_text=b'Recipient associated with that transaction'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='sender',
            field=models.ForeignKey(related_name='transaction_airtimetopup', to=settings.AUTH_USER_MODEL, help_text=b'Sender associated with that transaction'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='state',
            field=models.CharField(default=b'INIT', help_text=b'State of the transaction.', max_length=4, verbose_name=b'State', choices=[(b'INIT', b'initialized'), (b'INFO', b'gatering information'), (b'REDY', b'ready for payment'), (b'PAID', b'paid'), (b'PROC', b'processed'), (b'CANC', b'cancelled'), (b'INVD', b'invalid')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.ForeignKey(related_name='transaction_transaction', to='pricing.ExchangeRate', help_text=b'Exchange rate applied to this transaction', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_processor',
            field=models.CharField(blank=True, help_text=b'Payment Processor used', max_length=4, verbose_name=b'Payment Processor', choices=[(b'PAYP', b'paypal'), (b'STRP', b'stripe'), (b'WPAY', b'wepay')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(help_text=b'Reference generated by payment processor', max_length=50, verbose_name=b'Payment Reference', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(related_name='transaction_transaction', to='recipient.Recipient', help_text=b'Recipient associated with that transaction'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(related_name='transaction_transaction', to=settings.AUTH_USER_MODEL, help_text=b'Sender associated with that transaction'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_charge',
            field=models.FloatField(help_text=b'Service charge of the transaction in USD', null=True, verbose_name=b'Service charge in USD', blank=True),
            preserve_default=True,
        ),
    ]
