# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20150526_2127'),
        ('recipient', '0002_auto_20150524_2158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0009_auto_20150619_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state', models.CharField(default=b'INIT', help_text=b'State of the transaction.', max_length=4, verbose_name=b'State', choices=[(b'INIT', b'initialized'), (b'INFO', b'gatering information'), (b'REDY', b'ready for payment'), (b'PAID', b'paid'), (b'PROC', b'processed'), (b'CANC', b'cancelled'), (b'INVD', b'invalid')])),
                ('reference_number', models.CharField(help_text=b'6-digit reference number given to the customer to refer to transaction in case of problems', max_length=6, verbose_name=b'Reference Number')),
                ('service_charge', models.FloatField(help_text=b'Service charge of the transaction in USD', null=True, verbose_name=b'Service charge in USD', blank=True)),
                ('cost_of_transaction_usd', models.FloatField(help_text=b'Cost of the transaction in USD.        This could be the cost of the service or product we pay for        on behalf of the sender.', null=True, verbose_name=b'Cost of transaction in USD', blank=True)),
                ('cost_of_transaction_ghs', models.FloatField(help_text=b'Cost of the transaction in GHS.', null=True, verbose_name=b'Cost of transaction in GHS', blank=True)),
                ('payment_processor', models.CharField(blank=True, help_text=b'Payment Processor used', max_length=4, verbose_name=b'Payment Processor', choices=[(b'PAYP', b'paypal'), (b'STRP', b'stripe'), (b'WPAY', b'wepay')])),
                ('payment_reference', models.CharField(help_text=b'Reference generated by payment processor', max_length=50, verbose_name=b'Payment Reference', blank=True)),
                ('last_changed', models.DateTimeField(help_text=b'Last changed', verbose_name=b'Last changed', auto_now_add=True)),
                ('description', models.CharField(help_text=b'Description of the valet request', max_length=500, verbose_name=b'Description', blank=True)),
                ('exchange_rate', models.ForeignKey(related_name='transaction_valettransaction', to='pricing.ExchangeRate', help_text=b'Exchange rate applied to this transaction', null=True)),
                ('recipient', models.ForeignKey(related_name='transaction_valettransaction', to='recipient.Recipient', help_text=b'Recipient associated with that transaction')),
                ('sender', models.ForeignKey(related_name='transaction_valettransaction', to=settings.AUTH_USER_MODEL, help_text=b'Sender associated with that transaction')),
            ],
            options={
                'ordering': ['-last_changed'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RenameField(
            model_name='airtimetopup',
            old_name='service_fee',
            new_name='airtime_service_fee',
        ),
        migrations.RemoveField(
            model_name='airtimetopup',
            name='amount_ghs',
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='cost_of_transaction_ghs',
            field=models.FloatField(help_text=b'Cost of the transaction in GHS.', null=True, verbose_name=b'Cost of transaction in GHS', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='cost_of_transaction_usd',
            field=models.FloatField(help_text=b'Cost of the transaction in USD.        This could be the cost of the service or product we pay for        on behalf of the sender.', null=True, verbose_name=b'Cost of transaction in USD', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='service_charge',
            field=models.FloatField(help_text=b'Service charge of the transaction in USD', null=True, verbose_name=b'Service charge in USD', blank=True),
            preserve_default=True,
        ),
    ]
