# Error Status Codes
INVALID_PARAMETERS = '0'
PASSWORD_FORMAT = '1'
PASSWORD_MISMATCH = '2'
PRIVACY_POLICY_NOT_ACCEPTED = '3'
EMAIL_IN_USE = '4'
EMAIL_IN_USE_UNCONFIRMED = '5'
ACTIVATION_KEY_INVALID = '6'
ACTIVATION_KEY_EXPIRED = '7'
ACTIVATION_KEY_NOT_EXPIRED = '8'
EMAIL_UNKNOWN = '9'
USER_ACCOUNT_ALREADY_ACTIVATED = '10'
USER_ACCOUNT_DISABLED = '11'
USER_ACCOUNT_NOT_ACTIVATED_YET = '12'
SIGNIN_WRONG_CREDENTIALS = '13'
ADMIN_ACCOUNT = '14'
EMAIL_NOT_CHANGED = '15'
PASSWORD_OLD_INCORRECT = '16'
SIGNIN_FACEBOOK_NOT_LOGGED_IN = '17'
SIGNIN_FACEBOOK_NOT_VERIFIED = '18'
SIGNIN_FACEBOOK_NO_EMAIL = '19'
NO_PASSWORD_SET = '20'
PASSWORD_SET = '21'

PHONE = 'PHON'
EMAIL = 'MAIL'
SMS = 'SMS'
WHATSAPP = 'WAP'

CONTACT_METHODS = (PHONE, EMAIL, SMS, WHATSAPP)

TRUSTED = 'TRST'
FRAUDULENT = 'FRAD'
NEUTRAL = 'NEUT'

TRUST_STATUSES = (
    (TRUSTED, 'Trusted'),
    (FRAUDULENT, 'Fraudulent'),
    (NEUTRAL, 'Neutral')
)
