# Error Status Codes
INVALID_PARAMETERS = '0'
PASSWORD_FORMAT = '1'
PASSWORD_MISMATCH = '2'
PRIVACY_POLICY_NOT_ACCEPTED = '3'
EMAIL_IN_USE = '4'
EMAIL_IN_USE_UNCONFIRMED = '5'
ACTIVATION_KEY_INVALID = '6'
ACTIVATION_KEY_EXPIRED = '7'
ACTIVATION_KEY_NOT_EXPIRED = '8'
EMAIL_UNKNOWN = '9'
USER_ACCOUNT_ALREADY_ACTIVATED = '10'
USER_ACCOUNT_DISABLED = '11'

# PASSWORD_OLD_INCORRECT = '3'
# EMAIL_NOT_CHANGED = '6'
# USER_NOT_FOUND = '7'
# USER_ACCOUNT_NOT_ACTIVATED_YET = '8'



# SIGNIN_WRONG_CREDENTIALS = '13'
# SIGNIN_MISSING_CREDENTIALS = '14'
# ADMIN_ACCOUNT = '16'
# USER_PROFILE_INCOMPLETE = '17'