from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from beam_value.utils import mails

from pricing.models import ExchangeRate, AirtimeServiceFee

from recipient.models import Recipient


class AirtimeTopup(models.Model):

    class Meta:
        ordering = ['-initialized_at']

    # Constants
    VODAFONE = 'VOD'
    AIRTEL = 'AIR'
    MTN = 'MTN'
    TIGO = 'TIG'

    NETWORK_CHOICES = (
        (VODAFONE, 'Vodafone'),
        (AIRTEL, 'Airtel'),
        (MTN, 'MTN'),
        (TIGO, 'Tigo')
    )

    INIT = 'INIT'
    PAID = 'PAID'
    PROCESSED = 'PROC'
    CANCELLED = 'CANC'
    INVALID = 'INVD'

    TRANSACTION_STATES = (
        (INIT, 'initialized'),
        (PAID, 'paid'),
        (PROCESSED, 'processed'),
        (CANCELLED, 'cancelled'),
        (INVALID, 'invalid')
    )

    STRIPE = 'STRP'

    PAYMENT_PROCESSOR_CHOICES = (
        (STRIPE, 'stripe'),
    )

    sender = models.ForeignKey(
        User,
        related_name='artime_topups',
        help_text='Sender associated with that topup'
    )

    recipient = models.ForeignKey(
        Recipient,
        related_name='airtime_topups',
        help_text='Recipient associated with that transaction'
    )

    exchange_rate = models.ForeignKey(
        ExchangeRate,
        related_name='airtime_topup',
        help_text='Exchange rate applied to this topup'
    )

    service_fee = models.ForeignKey(
        AirtimeServiceFee,
        related_name='airtime_topup',
        help_text='Service fee applied to this topup'
    )

    network = models.CharField(
        'Network',
        max_length=4,
        choices=NETWORK_CHOICES,
        help_text='Phone Network'
    )

    amount_ghs = models.FloatField(
        'Amount in GHS',
        help_text='Topup amount in GHS.'
    )

    reference_number = models.CharField(
        'Reference Number',
        max_length=6,
        help_text='6-digit reference number given to the customer to refer ' +
                  'to transaction in case of problems'
    )

    comments = models.TextField(
        'Comments',
        blank=True,
        help_text='Leave comments when manually solving problems with this transaction'
    )

    state = models.CharField(
        'State',
        max_length=4,
        choices=TRANSACTION_STATES,
        default=INIT,
        help_text='State of the transaction.'
    )

    initialized_at = models.DateTimeField(
        'Initialized at',
        auto_now_add=True,
        help_text='Time at which transaction was created by sender'
    )

    paid_at = models.DateTimeField(
        'Paid at',
        null=True,
        blank=True,
        help_text='Time at which payment was confirmed with payment gateway'
    )

    processed_at = models.DateTimeField(
        'Processed at',
        null=True,
        blank=True,
        help_text='Time at which equivalent amount was sent to customer'
    )

    cancelled_at = models.DateTimeField(
        'Cancelled at',
        null=True,
        blank=True,
        help_text='Time at which the transaction was cancelled and rolled back'
    )

    invalidated_at = models.DateTimeField(
        'Invalidated at',
        null=True,
        blank=True,
        help_text='Time at which payment was set invalid'
    )

    payment_processor = models.CharField(
        'Payment Processor',
        max_length=4,
        blank=True,
        choices=PAYMENT_PROCESSOR_CHOICES,
        help_text='Payment Processor used'
    )

    payment_reference = models.CharField(
        'Payment Reference',
        max_length=50,
        blank=True,
        help_text='Reference generated by payment Processor'
    )

    @property
    def charge_usd(self):
        try:
            return self.service_fee.fee + self.amount_ghs / self.exchange_rate.usd_ghs
        except TypeError:
            return None

    def post_paid(self):

        mails.send_mail(
            subject_template_name=settings.MAIL_NOTIFY_ADMIN_PAID_SUBJECT,
            email_template_name=settings.MAIL_NOTIFY_ADMIN_PAID_TEXT,
            context={
                'domain': settings.ENV_SITE_MAPPING[settings.ENV][settings.SITE_API],
                'protocol': settings.PROTOCOL,
                'id': self.id
            },
            to_email=mails.get_admin_mail_addresses()
        )

    def post_processed(self):

        context = {
            'first_name': self.sender.first_name,
            'amount_ghs': self.amount_ghs,
            'phone_number': self.phone_number,
        }

        mails.send_mail(
            subject_template_name=settings.MAIL_AITRIME_TOPUP_COMPLETE_SUBJECT,
            email_template_name=settings.MAIL_AITRIME_TOPUP_COMPLETE_TEXT,
            context=context,
            from_email=settings.DEFAULT_FROM_EMAIL,
            to_email=self.sender.email,
            html_email_template_name=settings.MAIL_AITRIME_TOPUP_COMPLETE_HTML
        )


class Transaction(models.Model):

    class Meta:
        ordering = ['-last_changed']

    # Constants
    INIT = 'INIT'
    GATHERING_INFO = 'INFO'
    READY_FOR_PAYMENT = 'REDY'
    PAID = 'PAID'
    PROCESSED = 'PROC'
    CANCELLED = 'CANC'
    INVALID = 'INVD'

    TRANSACTION_STATES = (
        (INIT, 'initialized'),
        (GATHERING_INFO, 'gatering information'),
        (READY_FOR_PAYMENT, 'ready for payment'),
        (PAID, 'paid'),
        # Fulfillment completed by Beam
        (PROCESSED, 'processed'),
        # Could not be completed
        (CANCELLED, 'cancelled'),
        # Error during payment
        (INVALID, 'invalid')
    )

    UTILITY_BILL = 'UTIL'
    GIFT = 'GIFT'
    SCHOOL_FEE = 'SCHL'
    HOSPITAL_BILL = 'HOSP'
    INTERNET = 'INTR'
    ERRAND = 'ERRD'
    OTHER = 'OTHR'

    TRANSACTION_TYPES = (
        (UTILITY_BILL, 'utility bill'),
        (GIFT, 'gift'),
        (SCHOOL_FEE, 'school fee'),
        (HOSPITAL_BILL, 'hospital bill'),
        (INTERNET, 'internet'),
        (ERRAND, 'errand'),
        (OTHER, 'other')
    )

    PAYPAL = 'PAYP'
    STRIPE = 'STRP'

    PAYMENT_PROCESSOR_CHOICES = (
        (PAYPAL, 'paypal'),
        (STRIPE, 'stripe')
    )

    sender = models.ForeignKey(
        User,
        related_name='transactions',
        help_text='Sender associated with that transaction'
    )

    recipient = models.ForeignKey(
        Recipient,
        related_name='transactions',
        help_text='Recipient associated with that transaction'
    )

    transaction_type = models.CharField(
        'Type',
        max_length=4,
        choices=TRANSACTION_TYPES,
        default=OTHER,
        help_text='Categorization of service'
    )

    additional_info = models.CharField(
        'Additional Information',
        max_length=500,
        blank=True,
        help_text='Additional Information provided by user'
    )

    exchange_rate = models.ForeignKey(
        ExchangeRate,
        related_name='transaction',
        help_text='Exchange Rates applied to this transaction'
    )

    cost_of_delivery_usd = models.FloatField(
        'Cost of Delivery in USD',
        blank=True,
        null=True,
        help_text='Cost of the transaction in USD.'
    )

    cost_of_delivery_ghs = models.FloatField(
        'Cost of Delivery in GHS',
        blank=True,
        null=True,
        help_text='Cost of the transaction in GHS.'
    )

    service_charge = models.FloatField(
        'Service Charge in USD',
        blank=True,
        null=True,
        help_text='Service Charge of the transaction in USD'
    )

    reference_number = models.CharField(
        'Reference Number',
        max_length=6,
        help_text='6-digit reference number given to the customer to refer ' +
                  'to transaction in case of problems'
    )

    state = models.CharField(
        'State',
        max_length=4,
        choices=TRANSACTION_STATES,
        default=INIT,
        help_text='State of the transaction.'
    )

    last_changed = models.DateTimeField(
        'Last changed',
        auto_now_add=True,
        help_text='Last changed'
    )

    payment_processor = models.CharField(
        'Payment Processor',
        max_length=4,
        blank=True,
        choices=PAYMENT_PROCESSOR_CHOICES,
        help_text='Payment Processor used'
    )

    payment_reference = models.CharField(
        'Payment Reference',
        max_length=50,
        blank=True,
        help_text='Reference generated by payment Processor'
    )

    def add_status_change(self, comment, author='user'):
        comment = Comment(
            transaction=self,
            author=author,
            comment=comment
        )

        comment.save()

    def save(self, *args, **kwargs):
        self.last_changed = timezone.now()
        super(Transaction, self).save(*args, **kwargs)

    @property
    def charge_usd(self):
        try:
            return self.cost_of_delivery_usd + self.service_charge
        except TypeError:
            return None


class Comment(models.Model):

    class Meta:
        ordering = ['-timestamp']

    transaction = models.ForeignKey(
        Transaction,
        related_name='comments',
        help_text='Transaction associated with comment.'
    )

    author = models.CharField(
        'Author',
        max_length=50,
        help_text='Author of comment'
    )

    timestamp = models.DateTimeField(
        'Timestamp',
        auto_now_add=True,
        help_text='Timestamp of comment'
    )

    comment = models.CharField(
        'Comment',
        max_length=300,
        help_text='The comment itself'
    )
